http:
  middlewares:
    auth-middleware:
      forwardAuth:
        address: "${AUTH_VALIDATE_URL}"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-User-Id"
          - "X-Username"
          - "X-User-Role"
        authRequestHeaders:
          - "Authorization"
          - "Cookie"
    
    upload-strip:
      stripPrefix:
        prefixes:
          - "/upload"

  routers:
    upload:
      rule: "PathPrefix(`/upload`)"
      middlewares:
        - auth-middleware
        - upload-strip
      service: upload-service

  services:
    upload-service:
      loadBalancer:
        servers:
          - url: "${UPLOAD_AZURE_URL}"
        passHostHeader: false
