entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml    
    watch: true

api:
  dashboard: true
  insecure: true
