name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-service:
    name: Upload Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/upload-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/upload-service

  process-service:
    name: Process Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/process-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/process-service
    
  metadata-service:
    name: Metadata Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/metadata-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/metadata-service

