name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  upload-service-tests:
    name: Upload Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/upload-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/upload-service

  process-service-tests:
    name: Process Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/process-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/process-service

  metadata-service-tests:
    name: Metadata Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: ./TranscodeX.Backend/metadata-service
      - name: Run tests
        run: npm test
        working-directory: ./TranscodeX.Backend/metadata-service

  docker-build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    needs:
      - upload-service-tests
      - process-service-tests
      - metadata-service-tests
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push upload-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transcodex-upload-service:latest ./TranscodeX.Backend/upload-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/transcodex-upload-service:latest

      - name: Build and push process-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transcodex-process-service:latest ./TranscodeX.Backend/process-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/transcodex-process-service:latest

      - name: Build and push metadata-service image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/transcodex-metadata-service:latest ./TranscodeX.Backend/metadata-service
          docker push ${{ secrets.DOCKER_USERNAME }}/transcodex-metadata-service:latest
